--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/enigma/Documentos/WallPapers/fondo.png"

-- Special
background="#0a1017"
foreground="#c1c3c5"
cursor="#c1c3c5"

-- Colors
color0="#0a1017"
color1="#6D6B6D"
color2="#44718A"
color3="#837E83"
color4="#4C9CBE"
color5="#959396"
color6="#9EA5AE"
color7="#c1c3c5"
color8="#59626d"
color9="#6D6B6D"
color10="#44718A"
color11="#837E83"
color12="#4C9CBE"
color13="#959396"
color14="#9EA5AE"
color15="#c1c3c5"
