# Shell variables
# Generated by 'wal'
wallpaper="/home/enigma/Documentos/WallPapers/fondo.png"

# Special
background='#0a1017'
foreground='#c1c3c5'
cursor='#c1c3c5'

# Colors
color0='#0a1017'
color1='#6D6B6D'
color2='#44718A'
color3='#837E83'
color4='#4C9CBE'
color5='#959396'
color6='#9EA5AE'
color7='#c1c3c5'
color8='#59626d'
color9='#6D6B6D'
color10='#44718A'
color11='#837E83'
color12='#4C9CBE'
color13='#959396'
color14='#9EA5AE'
color15='#c1c3c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
